"""add_order_index_to_meanings

Revision ID: b5d07521ac45
Revises: 066a7715b5b6
Create Date: 2026-03-31 00:32:14.521500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d07521ac45'
down_revision: Union[str, None] = '066a7715b5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meanings', sa.Column('order_index', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meanings', 'order_index')
    # ### end Alembic commands ###
